### ISSUE TITLE
希望区分删除和撤销

### ISSUE THREAD

**Issue by dba-ming** [Zuoqiu-Yingyi/siyuan-plugin-inbox#10]
希望区分删除和撤回。
删除后，就没有 “此消息已删除”的提示，直接无痕删除。
撤回后，可以有个  “此消息已撤回”的提示。

**Comment by Zuoqiu-Yingyi** [comment]
注: 受所使用的第三方组件的限制, 目前实现的消息撤回功能有如下特点
- 撤回的消息不会删除相应的消息内容, 仅在前台将该消息标记为 `已撤回` 且不显示内容
- 撤回的消息不能再调出消息操作菜单, 因此没法在前台删除已撤回的消息
