### ISSUE TITLE
Docker 版本貌似无法使用

### ISSUE THREAD

**Issue by GodDown1V4** [Zuoqiu-Yingyi/siyuan-plugin-inbox#12]
已在群晖上部署思源笔记，安装改插件后无法通过 http(s)://host[:port]/plugin/inbox/apps/inbox.html 访问，提示 HTTP ERROR 404

**Comment by Zuoqiu-Yingyi** [comment]
这是因为当时打包时文档有问题，URL 路径应该是 `http(s)://host[:port]/plugins/inbox/apps/inbox.html`

**Comment by myg321** [comment]
> 这是因为当时打包时文档有问题，URL 路径应该是 这是因为当时打包时文档有问题，URL 路径应该是 这是因为当时打包时文档有问题，URL 路径应该是 `http(s)://host[:port]/plugins/inbox/apps/inbox.html`

建议老哥这个路径在思源插件简介处改一下吧，搞了半天一直无法正常打开，在这里才看到原来inbox少了一个s😥
