### ISSUE TITLE
无法换行

### ISSUE THREAD

**Issue by dba-ming** [Zuoqiu-Yingyi/siyuan-plugin-inbox#9]
shift+enter 无法实现换行。
一般是 enter  发送，shift+enter  换行。

**Comment by Zuoqiu-Yingyi** [comment]
输入框中换行需要先按住 <kbd>Shift</kbd> 后再点击 <kbd>Enter</kbd>, 之后依次松开 <kbd>Enter</kbd>, <kbd>Shift</kbd>
